"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var point_1 = require("./point");
var calculateDistance_1 = require("./calculateDistance");
var calcularQuadrant_1 = require("./calcularQuadrant");
var mYPoint = new point_1.Point(40, 60);
var distancia_X2_Y2 = new point_1.Point(22, 44);
console.log(mYPoint.getx());
console.log();
console.log(mYPoint.gety());
mYPoint.setx(100);
mYPoint.sety(200);
console.log();
console.log(mYPoint.getx());
console.log();
console.log(mYPoint.gety());
console.log();
console.log((0, calculateDistance_1.calculateDistance)(distancia_X2_Y2));
console.log();
console.log((0, calcularQuadrant_1.calcularQuadrant)(0, 0));
console.log((0, calcularQuadrant_1.calcularQuadrant)(-5, -10));
console.log((0, calcularQuadrant_1.calcularQuadrant)(-5, 10));
console.log((0, calcularQuadrant_1.calcularQuadrant)(-5, -10));
console.log((0, calcularQuadrant_1.calcularQuadrant)(5, -10));
